name: 'Compile Arduino Sketch'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'

      - name: 'Set up Python'
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.x'

      - name: 'Install arduino-cli'
        run: |
          pip install arduino-cli
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: 'Install libraries'
        run: |
          arduino-cli lib install 'WiFi'
          arduino-cli lib install 'HTTPClient'
          arduino-cli lib install 'WiFiManager'
          arduino-cli lib install 'ArduinoJson'

      - name: 'Compile sketch'
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 src/sketch.ino --output-dir ./build

      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'compiled-sketch'
          path: './build/sketch.ino.bin'
