name: 'Compile Arduino Sketch'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'

      - name: 'Set up Arduino CLI'
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: 'Install WiFi library'
        run: arduino-cli lib install 'WiFi'

      - name: 'Install HTTPClient library'
        run: arduino-cli lib install 'HTTPClient'

      - name: 'Install WiFiManager library'
        run: arduino-cli lib install 'WiFiManager'

      - name: 'Install ArduinoJson library'
        run: arduino-cli lib install 'ArduinoJson'

      - name: 'Compile sketch'
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 src/sketch.ino --output-dir ./build

      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'compiled-sketch'
          path: './build/sketch.ino.bin'
